### ISSUE TITLE
[Bug Report] AppCymple Crashes When ESP32 Connection Lost

### ISSUE THREAD

**Issue by m-RNA** [Dominocs/Project_Cymple#2]
Hello, I found a bug which make appCymple crashes if the ESP32 disconnects due to network issues or power loss.

**Steps to Reproduce:**

1.  Don't open VRCFaceTrcaking
2. Connect ESP32 to WLAN.
3. Transmit data.
4. Interrupt connection (network instability or power off ESP32).
5. AppCymple crashes.

**Environment:**
Ver: 0.0.1

I have experience in Qt C++ development for upper computer applications. I am interested in contributing to the project if appCymple is open-sourced.

Thanks for considering my request.

**Comment by Dominocs** [comment]
是的这是个已知的bug，如果你介意的话可以在QQ群开放后进入获取之前的稳定版本，QQ群将在近期扩展人数。
由于其不影响正常流程，规划其会在之后优化模型时才会一同修复。
cymple客户端目前暂时还不考虑公布代码，感谢关注
